version: '3'

services:
  web:
    build: .
    command: gunicorn web_page1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=web_page1_user
      - POSTGRES_PASSWORD=web_page1_password
      - POSTGRES_DB=web_page1_dev

volumes:
  postgres_data: